version: '3.8'

services:
  node1:
    build: .
    container_name: synapsenet-node1
    volumes:
      - node1-data:/data
    ports:
      - "9001:9000"
    command: ["--data-dir", "/data/.synapsenet"]
    networks:
      - synapsenet

  node2:
    build: .
    container_name: synapsenet-node2
    volumes:
      - node2-data:/data
    ports:
      - "9002:9000"
    command: ["--data-dir", "/data/.synapsenet"]
    networks:
      - synapsenet

  node3:
    build: .
    container_name: synapsenet-node3
    volumes:
      - node3-data:/data
    ports:
      - "9003:9000"
    command: ["--data-dir", "/data/.synapsenet"]
    networks:
      - synapsenet

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  synapsenet:
    driver: bridge
